

<?php
/**
 * @file
 * This is the main module file.
 */

drupal_add_js(drupal_get_path('module', 'loremimage') . '/loremimage.js');

/**
* Implementation of hook_menu().
*/
function loremimage_menu() {
  $items['loremimage'] = array(
        'type' => MENU_CALLBACK,
        'access arguments' => array('access content'),
        'page callback' => 'drupal_get_form',
        'page arguments'=>array('loremimage_form'));

  return $items;
}

function loremimage_form() {
    $form = array();


    $form['xwidth']=array(
        '#type'=>'textfield',
        '#title'=>t('The Image\'s X dimensions (width):')
      );
    $form['yheight']=array(
        '#type'=>'textfield',
        '#title'=>t('The Image\'s Y dimensions (height)')
      );


    $form['category']=array(
        '#type'=>'select',
        '#title'=>t('Category'),
        '#options'=>array('Abstract', 'City', 'People', 'Transport', 'Animals', 'Food', 'Nature', 'Business', 'Cats', 'Fashion', 'Technics')
      );
	 
     $form['color']=array(
        '#type'=>'radios',
        '#title'=>t('Color'),
	   '#options' => array(
		t('Color'),
		t('Greyscale'))
      );

     $form['email']=array(
        '#type'=>'textarea',
        '#title'=>t('DummyText'),
	   '#cols' => 60,
	   '#rows' => 10,
	   '#resizable' => FALSE
      );


    $form['submit']=array(
        '#type'=>'submit',
        '#value'=>t('Submit'),
	   '#attributes' => array(
    	   'onclick' => "sendToLoremImage(); return false;")
      );

      return $form;
}
